// <auto-generated />
using System;
using MLOps_Dashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MLOps_Dashboard.Migrations
{
    [DbContext(typeof(MLOpsContext))]
    [Migration("20260530135457_ExpandData")]
    partial class ExpandData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MLOps_Dashboard.Models.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Architectures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ensemble decision trees",
                            Name = "Random Forest"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Deep residual network",
                            Name = "CNN (ResNet-18)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gradient boosted trees",
                            Name = "XGBoost"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Time-series recurrent network",
                            Name = "LSTM"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Attention-based NLP model",
                            Name = "Transformer (BERT)"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Support Vector Machine",
                            Name = "SVM (Linear)"
                        });
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeaturesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Datasets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeaturesCount = 784,
                            Name = "MNIST (Digits)",
                            Rows = 70000
                        },
                        new
                        {
                            Id = 2,
                            FeaturesCount = 12,
                            Name = "Titanic Survival",
                            Rows = 891
                        },
                        new
                        {
                            Id = 3,
                            FeaturesCount = 45,
                            Name = "S&P 500 Daily Options",
                            Rows = 250000
                        },
                        new
                        {
                            Id = 4,
                            FeaturesCount = 3072,
                            Name = "CIFAR-10",
                            Rows = 60000
                        },
                        new
                        {
                            Id = 5,
                            FeaturesCount = 30,
                            Name = "Credit Card Fraud",
                            Rows = 284807
                        });
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Hyperparameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.ToTable("Hyperparameters");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TrainingTimeMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("DatasetId");

                    b.ToTable("TrainingRuns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 0.94099999999999995,
                            ArchitectureId = 1,
                            DatasetId = 1,
                            Timestamp = new DateTime(2026, 5, 20, 15, 54, 56, 42, DateTimeKind.Local).AddTicks(6426),
                            TrainingTimeMs = 12000.0
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 0.99299999999999999,
                            ArchitectureId = 2,
                            DatasetId = 1,
                            Timestamp = new DateTime(2026, 5, 21, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(546),
                            TrainingTimeMs = 340000.0
                        },
                        new
                        {
                            Id = 3,
                            Accuracy = 0.91500000000000004,
                            ArchitectureId = 6,
                            DatasetId = 1,
                            Timestamp = new DateTime(2026, 5, 22, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(593),
                            TrainingTimeMs = 4500.0
                        },
                        new
                        {
                            Id = 4,
                            Accuracy = 0.82099999999999995,
                            ArchitectureId = 1,
                            DatasetId = 2,
                            Timestamp = new DateTime(2026, 5, 23, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(601),
                            TrainingTimeMs = 800.0
                        },
                        new
                        {
                            Id = 5,
                            Accuracy = 0.84499999999999997,
                            ArchitectureId = 3,
                            DatasetId = 2,
                            Timestamp = new DateTime(2026, 5, 24, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(607),
                            TrainingTimeMs = 1200.0
                        },
                        new
                        {
                            Id = 6,
                            Accuracy = 0.53100000000000003,
                            ArchitectureId = 1,
                            DatasetId = 3,
                            Timestamp = new DateTime(2026, 5, 25, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(612),
                            TrainingTimeMs = 85000.0
                        },
                        new
                        {
                            Id = 7,
                            Accuracy = 0.59199999999999997,
                            ArchitectureId = 4,
                            DatasetId = 3,
                            Timestamp = new DateTime(2026, 5, 26, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(616),
                            TrainingTimeMs = 920000.0
                        },
                        new
                        {
                            Id = 8,
                            Accuracy = 0.56499999999999995,
                            ArchitectureId = 3,
                            DatasetId = 3,
                            Timestamp = new DateTime(2026, 5, 27, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(621),
                            TrainingTimeMs = 110000.0
                        },
                        new
                        {
                            Id = 9,
                            Accuracy = 0.94199999999999995,
                            ArchitectureId = 2,
                            DatasetId = 4,
                            Timestamp = new DateTime(2026, 5, 28, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(626),
                            TrainingTimeMs = 1850000.0
                        },
                        new
                        {
                            Id = 10,
                            Accuracy = 0.45000000000000001,
                            ArchitectureId = 1,
                            DatasetId = 4,
                            Timestamp = new DateTime(2026, 5, 29, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(630),
                            TrainingTimeMs = 45000.0
                        },
                        new
                        {
                            Id = 11,
                            Accuracy = 0.999,
                            ArchitectureId = 3,
                            DatasetId = 5,
                            Timestamp = new DateTime(2026, 5, 30, 15, 54, 56, 48, DateTimeKind.Local).AddTicks(635),
                            TrainingTimeMs = 34000.0
                        },
                        new
                        {
                            Id = 12,
                            Accuracy = 0.98499999999999999,
                            ArchitectureId = 6,
                            DatasetId = 5,
                            Timestamp = new DateTime(2026, 5, 30, 10, 54, 56, 48, DateTimeKind.Local).AddTicks(639),
                            TrainingTimeMs = 12000.0
                        });
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Hyperparameter", b =>
                {
                    b.HasOne("MLOps_Dashboard.Models.Architecture", "Architecture")
                        .WithMany("Hyperparameters")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architecture");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.TrainingRun", b =>
                {
                    b.HasOne("MLOps_Dashboard.Models.Architecture", "Architecture")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLOps_Dashboard.Models.Dataset", "Dataset")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architecture");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Architecture", b =>
                {
                    b.Navigation("Hyperparameters");

                    b.Navigation("TrainingRuns");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Dataset", b =>
                {
                    b.Navigation("TrainingRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
