// <auto-generated />
using System;
using MLOps_Dashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MLOps_Dashboard.Migrations
{
    [DbContext(typeof(MLOpsContext))]
    [Migration("20260529203657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MLOps_Dashboard.Models.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Architectures");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeaturesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Hyperparameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.ToTable("Hyperparameters");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TrainingTimeMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("DatasetId");

                    b.ToTable("TrainingRuns");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Hyperparameter", b =>
                {
                    b.HasOne("MLOps_Dashboard.Models.Architecture", "Architecture")
                        .WithMany("Hyperparameters")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architecture");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.TrainingRun", b =>
                {
                    b.HasOne("MLOps_Dashboard.Models.Architecture", "Architecture")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLOps_Dashboard.Models.Dataset", "Dataset")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architecture");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Architecture", b =>
                {
                    b.Navigation("Hyperparameters");

                    b.Navigation("TrainingRuns");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Dataset", b =>
                {
                    b.Navigation("TrainingRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
