// <auto-generated />
using System;
using MLOps_Dashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MLOps_Dashboard.Migrations
{
    [DbContext(typeof(MLOpsContext))]
    partial class MLOpsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MLOps_Dashboard.Models.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Architectures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ensemble decision trees",
                            Name = "Random Forest"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard CNN for image classification",
                            Name = "Convolutional Neural Network"
                        });
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeaturesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Datasets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeaturesCount = 784,
                            Name = "MNIST",
                            Rows = 70000
                        },
                        new
                        {
                            Id = 2,
                            FeaturesCount = 12,
                            Name = "Titanic",
                            Rows = 891
                        });
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Hyperparameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.ToTable("Hyperparameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchitectureId = 1,
                            Key = "n_estimators",
                            Value = "100"
                        });
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TrainingTimeMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("DatasetId");

                    b.ToTable("TrainingRuns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 0.98499999999999999,
                            ArchitectureId = 2,
                            DatasetId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingTimeMs = 45000.0
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 0.82099999999999995,
                            ArchitectureId = 1,
                            DatasetId = 2,
                            Timestamp = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingTimeMs = 1200.0
                        });
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Hyperparameter", b =>
                {
                    b.HasOne("MLOps_Dashboard.Models.Architecture", "Architecture")
                        .WithMany("Hyperparameters")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architecture");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.TrainingRun", b =>
                {
                    b.HasOne("MLOps_Dashboard.Models.Architecture", "Architecture")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MLOps_Dashboard.Models.Dataset", "Dataset")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architecture");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Architecture", b =>
                {
                    b.Navigation("Hyperparameters");

                    b.Navigation("TrainingRuns");
                });

            modelBuilder.Entity("MLOps_Dashboard.Models.Dataset", b =>
                {
                    b.Navigation("TrainingRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
